query pastWeek($from: ISO8601DateTime!, $to: ISO8601DateTime!) {
  viewer {
    workingActivity {
      id
      description
      startedAt
      stoppedAt
      project {
        id
        name
        color
      }
    }
    activities(from: $from, to: $to) {
      id
      description
      startedAt
      stoppedAt
      project {
        id
        name
        color
      }
    }
  }
}
